apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: {{ .Values.service.portName }}
      protocol: TCP
      port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.containerPort }}